# Generated by Django 4.2.7 on 2023-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("timestamp", models.IntegerField(default=0)),
                ("brief", models.CharField(max_length=500, null=True)),
            ],
            options={
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockId", models.CharField(max_length=20, null=True)),
                ("tradingVolume", models.IntegerField(default=0)),
                ("highestPrice", models.FloatField(default=0)),
                ("lowestPrice", models.FloatField(default=0)),
                ("openingPrice", models.FloatField(default=0)),
                ("closingPrice", models.FloatField(default=0)),
                ("timestamp", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "stockData",
            },
        ),
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "stockId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("stockName", models.CharField(max_length=50, null=True)),
                ("companyName", models.CharField(max_length=50, null=True)),
                ("information", models.CharField(max_length=500, null=True)),
            ],
            options={
                "db_table": "stockInfo",
            },
        ),
    ]
