# Generated by Django 4.2.7 on 2023-11-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("privilege", models.CharField(max_length=20, null=True)),
                ("balance", models.FloatField(default=0)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="OrderOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockId", models.CharField(max_length=20, null=True)),
                ("buyOrSell", models.BooleanField(default=False)),
                ("orderNum", models.IntegerField(default=0)),
                ("price", models.FloatField(default=0)),
                ("time", models.IntegerField(default=0)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "order_of_user",
            },
        ),
        migrations.CreateModel(
            name="FavorOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockId", models.CharField(max_length=20, null=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "favor_of_user",
            },
        ),
        migrations.CreateModel(
            name="StockOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockId", models.CharField(max_length=20, null=True)),
                ("holdNum", models.IntegerField(default=0)),
                ("spendMoney", models.FloatField(default=0)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "stock_of_user",
                "unique_together": {("userId", "stockId")},
            },
        ),
    ]
